// Generated by CoffeeScript 1.8.0

/*
  lib/responder/responder-process.coffee
 */

(function() {
  var AutocompleteUtils, ResponderBuffer, buffer, recv, send, utils, _;

  _ = require('underscore-plus');

  AutocompleteUtils = require('../js/autocomplete-utils');

  ResponderBuffer = require('../js/responder-buffer');

  utils = new AutocompleteUtils;

  buffer = new ResponderBuffer;

  send = function(msg) {
    return process.stdout.write(JSON.stringify({
      msg: msg
    }) + '\n');
  };

  recv = function(msg) {
    console.log('----', msg.cmd, '----');
    console.log(msg.text.replace(/\n/g, '\\n'));
    switch (msg.cmd) {
      case 'bufferEdit':
        return buffer.applyChg(msg);
      case 'newEditor':
        return buffer = new ResponderBuffer(msg.text);
      case 'noActiveEditor':
        return buffer = null;
      default:
        return console.log('responder, unknown msg cmd:', msg);
    }
  };

  process.stdin.on('data', function(data) {
    var obj, _i, _len, _ref, _results;
    _ref = utils.recvDemuxObj(data, true);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      obj = _ref[_i];
      _results.push(recv(obj));
    }
    return _results;
  });

  send('child-process spawned');

}).call(this);
