// Generated by CoffeeScript 1.8.0

/*
  lib/child-process.coffee
 */

(function() {
  var localUtils, recv, send, _;

  _ = require('underscore-plus');

  localUtils = require('./local-utils');

  send = function(msg) {
    return process.stdout.write(JSON.stringify({
      msg: msg
    }) + '\n');
  };

  recv = function(msg) {
    return console.log('MSG to child:', msg);
  };

  process.stdin.on('data', function(data) {
    var obj, _i, _len, _ref, _results;
    _ref = localUtils.recvDemuxObj(data, true);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      obj = _ref[_i];
      _results.push(recv(obj));
    }
    return _results;
  });

  send('child-process spawned');

}).call(this);
