// Generated by CoffeeScript 1.8.0

/*
  lib/child-process.coffee
 */

(function() {
  var send;

  send = function(msg) {
    return process.stdout.write(JSON.stringify(msg) + '\n');
  };

  process.stdin.on('data', function(msgText) {
    var err, obj;
    try {
      obj = JSON.parse(msgText.slice(0, -1));
    } catch (_error) {
      err = _error;
      console.log('child-process error parsing msg from atom:', err.message, '\n', msg);
      return;
    }
    return send(obj);
  });

  send('child-process spawned');

}).call(this);
