// Generated by CoffeeScript 1.8.0

/*
  lib/responder/responder-buffer.coffee
 */

(function() {
  var ResponderBuffer;

  module.exports = ResponderBuffer = (function() {
    function ResponderBuffer() {
      this.lines = [];
    }

    ResponderBuffer.prototype.setText = function(text) {
      return this.lines = text.split('\n');
    };

    ResponderBuffer.prototype.applyChg = function(chg) {
      var bufferDelta, chgLinEnd, chgLinStrt, cmd, cursor, cursorColumn, cursorRow, event, text;
      cmd = chg.cmd, text = chg.text, event = chg.event, cursor = chg.cursor;
      cursorRow = cursor.row, cursorColumn = cursor.column;
      return chgLinStrt = event.start, chgLinEnd = event.end, bufferDelta = event.bufferDelta, event;
    };

    return ResponderBuffer;

  })();

}).call(this);
